# Generated by Django 4.2.7 on 2023-11-28 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 11, 28, 21, 30, 16, 348626), verbose_name='Опубликована'),
        ),
    ]
