# Generated by Django 4.2.7 on 2023-12-09 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0087_alter_blog_posted_alter_comment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя пользователя')),
                ('site_rating', models.CharField(choices=[('1', 'Ужасно'), ('2', 'Плохо'), ('3', 'Средне'), ('4', 'Хорошо'), ('5', 'Отлично')], max_length=1, verbose_name='Оценка сайта')),
                ('feedback_text', models.TextField(verbose_name='Отзыв')),
                ('likes_merch', models.BooleanField(default=False, verbose_name='Нравится мерч')),
                ('likes_community', models.BooleanField(default=False, verbose_name='Нравится сообщество')),
                ('favorite_game', models.CharField(blank=True, max_length=40, null=True, verbose_name='Любимая игра')),
                ('suggestions', models.CharField(blank=True, max_length=30, null=True, verbose_name='Ваши пожелания')),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 9, 20, 17, 41, 373333), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 9, 20, 17, 41, 373333), verbose_name='Дата комментария'),
        ),
    ]
