# Generated by Django 4.2.7 on 2023-12-09 21:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0097_alter_blog_posted_alter_comment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'отзыв', 'verbose_name_plural': 'отзывы'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 10, 0, 21, 19, 558389), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 10, 0, 21, 19, 559385), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='favorite_game',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Любимая игра'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_text',
            field=models.TextField(verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='likes_community',
            field=models.BooleanField(verbose_name='Нравится сообщество'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='likes_merch',
            field=models.BooleanField(verbose_name='Нравится мерч'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='site_rating',
            field=models.CharField(choices=[('1', 'Ужасно'), ('2', 'Плохо'), ('3', 'Средне'), ('4', 'Хорошо'), ('5', 'Отлично')], max_length=1, verbose_name='Оценка сайта'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='suggestions',
            field=models.CharField(blank=True, choices=[('Разнообразие мерча', 'Разнообразие мерча'), ('Добавление программы лояльности', 'Добавление программы лояльности'), ('Больше информативности', 'Больше информативности')], max_length=50, null=True, verbose_name='Пожелания'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
    ]
