# Generated by Django 4.2.7 on 2023-12-09 21:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0103_order_alter_blog_posted_alter_comment_date_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 10, 0, 45, 35, 110930), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 10, 0, 45, 35, 111927), verbose_name='Дата комментария'),
        ),
    ]
