# Generated by Django 4.2.7 on 2023-12-10 00:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0129_alter_blog_posted_alter_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.CharField(default='no_image', max_length=255, verbose_name='Путь ко второму изображению'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 10, 3, 22, 14, 728111), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 10, 3, 22, 14, 729096), verbose_name='Дата комментария'),
        ),
    ]
